### ISSUE TITLE
다른 게임과 차별성

### ISSUE THREAD

**Issue by Hyodonjoo** [Hyodonjoo/VRarcher#5]
다른 학생들의 피드백으로 가장 많이 지적된 문제점 "다른 활 쏘는 게임과의 차별성이 보이지 않는다"입니다. 이에 대해 몇 개의 방안을 제안합니다
***
### 1-1. 오브젝트 model 적용
현재는 검은 구체로 하였으나, 다양한 model을 활용하여 활쏘는 재미를 증가
### 1-2. 오브젝트 행동
점수 오브젝트가 단순히 Field내에서 왕복으로 움직이는 것이 아니라, user에게 위협적인 행동을 한다거나, 공격을 하는 등의 긴장감을 조성
***
### 2-1. 화살의 다양화 
단순히 화살만 있는게 아니라, 불,전기,폭발 등 여러 특수 효과를 지는 화살을 플레이 도중 가끔 지급하여 재미를 증가
### 2-2. 활의 기능 다양화  
활을 한번에 여러개를 쏠 수 있거나, 폭격 지점 설정하듯이 화살이 맞은 곳에 범위 공격등 여러 기능
***
### 3-1. 맵의 다양화
현재 1개의 맵만 제작하였으나 여러 stage 제작
### 3-2 동물들의 공격성
가끔 동물들이 플레이어를 공격함
***
위 방안을 다 하자는 것은 아니고, 이 중에서 현실적인 문제와 타협하여 몇 개만 추가를 하고 싶습니다. 
문제를 개선하기 위해 제가 생각한 방안에 대해 코멘트를 남겨주셨으면 합니다. 물론 새로운 아이디어도 코멘트로 남겨주시거나, 새로운 issue로 등록해주세요

**Comment by Hyodonjoo** [comment]
## 다른 학생들이 남긴 코멘트입니다
***
- 구현 시 고려해야할 point가 있었으면 좋았을 것 같음
- 제자리에서 플레이 하는데 고개를 움직이는 것도 불가능한 것인지, 팔만 움직일 수 있는 것인지 궁금하다.
- 간단 명료하게 필요한 부분을 잘 설명했다고 생각함
- 주제의 참신성이 부족한 것 같다 유사한 장르가 많음
- 핵심이 짧고 굵게 잘 설명된 것 같습니다.
- 기존게임과 차별성이 없어보임
- 기존 양궁VR보다 얼마나 좋을지 궁금함
- 기존 앱에 비해 가지는 강점을 잘 모르겠음.
- 유사한 게임과이 차이가 무엇을 맞추느냐의 차이만 있다면 차별점이 크지 않다고 생각이 된다. 
- 기존 게임들과의 차별성을 주려면 맵 디자인, 모델 등이 중요할 것 같습니다.
- 제자리에서 하여 3d멀미가 심하지 않는다고 하셨는데 장애물이 정면에서만 오는 건지 궁금합니다. 만약 정면에서만 온다면 장애물을 저격하는 스릴있을 게임의 특성을 살리지 못할 것 같고 위나 옆에서 온다면 오히려 더 빠른 화면전환으로 멀미가 심할 것 같습니다.  
- 기존 vr 양궁과 fps게임을 섞은 느낌으로 보이며, 양궁 휠과 vr 컨트롤러의 조작감을 통일시켜 현실감을 주는 것을 주요적으로 설계해야할 것 같습니다.
- 기존 컨텐츠와의 차별점 부족 
- 다양한 활과 화살을 제공하고 장비마다 다양한 사운드를 제공하면 재밌을 것 같음
- 양궁을 현실에서 하는 것처럼 구현하는 것이 중요할 것 같다

**Comment by dooumsosil** [comment]
1. 추가 맵은 어떤 것이 괜찮을지 추천 부탁드립니다.
2. 동물이 공격하는 트리거가 플레이어가 가까이 왔을때로 지정해도 괜찮을까요?

**Comment by Hyodonjoo** [comment]
@dooumsosil 
> 1. 추가 맵은 어떤 것이 괜찮을지 추천 부탁드립니다.
> 2. 동물이 공격하는 트리거가 플레이어가 가까이 왔을때로 지정해도 괜찮을까요?

1. 일단 추가맵은 확정된 사항이 아니지만, 만약 추가맵을 제작하신다면 사막 지역 또는 설원 지역이 어떠실까요
2. 동물이 공격하는 트리거는 가까이 왔을 때로 지정하는 것이 아니라, 공격적인 동물(멧돼지 등)을 추가하는 것으로 생각하고 있습니다. 플레이중 계속 공격하면 불쾌함만 줄 테니 가끔식 등장하는 식으로 말이죠

일단 위 사항은 제안 사항일 뿐이라서 확정은 아닙니다만, 만약 제작을 완료하신다면 사용하도록 하겠습니다
